[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  branch = "https"
  name = "github.com/spothero/tools"

[[constraint]]
  name = "github.com/stianeikeland/go-rpio"
  version = "4.4.0"

[prune]
  go-tests = true
  unused-packages = true
