[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  revision = "a87cfbb5dd3e2f1f64f1e62aaa838e437a0aaae7"
  name = "github.com/spothero/tools"

[[constraint]]
  name = "github.com/stianeikeland/go-rpio"
  version = "4.4.0"

[prune]
  go-tests = true
  unused-packages = true
