"""empty message

Revision ID: e854dcdf6367
Revises: f8402255bbd7
Create Date: 2017-01-22 22:50:28.305817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e854dcdf6367'
down_revision = 'f8402255bbd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('_default_scopes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', '_default_scopes')
    # ### end Alembic commands ###
